- id: '1782068290653'
  alias: Hola Mundo - Test de humo
  description: Automatización de prueba para validar el pipeline de Home Assistant
  triggers:
  - trigger: time
    at: '14:10:00'
    weekday:
    - wed
    - sat
    - sun
    - fri
    - thu
    - tue
    - mon
  conditions: []
  actions:
  - action: persistent_notification.create
    metadata: {}
    data:
      message: ¡Hola mundo desde LUMEN!
      title: LUMEN
  mode: single
