services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./config:/config
    restart: unless-stopped
    ports:
      - "8123:8123"
  piper:
    container_name: piper
    image: "ghcr.io/rhasspy/wyoming-piper:2.2.2"
    restart: unless-stopped